### ISSUE TITLE
New release, please

### ISSUE THREAD

**Issue by tobiasherp** [collective/Products.NoDuplicateLogin#2]
Could we have a new release, please?

The [latest version currently on PyPI](https://pypi.org/project/Products.NoDuplicateLogin/) is still release 2.0; it doesn't include the manifest fix and thus doesn't contain the `www/noduplicateloginAdd.zpt` template which is needed to add the plugin.

(I don't know whether I'd have the necessary permissions on PyPI to do it myself.)

**Comment by tobiasherp** [comment]
It seems I can't upload to PyPI yet using my account (`TobiasHerp`):
```
$ twine upload -u TobiasHerp dist/Products.NoDuplicateLogin-2.0.1.tar.gz
Uploading distributions to https://pypi.org
Uploading Products.NoDuplicateLogin-2.0.1.tar.gz
100%|████| 19.9k/19.9k [00:00<00:00, 45.8kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 405 Client Error: Method Not Allowed for url: https://pypi.org/
```

Perhaps someone could add my user to the required PyPI organization, please?

**Comment by davisagli** [comment]
@tobiasherp The only people who might be able to give you access are the 2 existing maintainers on PyPI, @aclark4life and @MatthewWilkes

**Comment by aclark4life** [comment]
Will do! Give me a minute here.

**Comment by aclark4life** [comment]
Done! Enjoy

![Screenshot 2023-12-06 at 10 37 45 AM](https://github.com/collective/Products.NoDuplicateLogin/assets/72164/8144fe43-b1c5-4eb0-b834-4dce0cef1006)

**Comment by tobiasherp** [comment]
Thank you! We have a release now.
